# Read data

In [8]:
import pandas as pd

df = pd.read_csv('data1.csv')
df.head()

  Date;Berri 1;C'te-Sainte-Catherine;Maisonneuve 1;Maisonneuve 2;du Parc;Pierre-Dupuy;Rachel1;St-Urbain
0                    01/01/2012;35;0;38;51;26;10;16;
1                    02/01/2012;83;1;68;153;53;6;43;
2                  03/01/2012;135;2;104;248;89;3;58;
3                 04/01/2012;144;1;116;318;111;8;61;
4                 05/01/2012;197;2;124;330;97;13;95;

In [9]:
df = pd.read_csv('data1.csv', sep=';', encoding='latin1', parse_dates=['Date'], dayfirst=True, index_col='Date')
df.head()

,Berri 1,C'te-Sainte-Catherine,Maisonneuve 1,Maisonneuve 2,du Parc,Pierre-Dupuy,Rachel1,St-Urbain
Date,,,,,,,,
2012-01-01,35,0,38,51,26,10,16,NaN
2012-01-02,83,1,68,153,53,6,43,NaN
2012-01-03,135,2,104,248,89,3,58,NaN
2012-01-04,144,1,116,318,111,8,61,NaN
2012-01-05,197,2,124,330,97,13,95,NaN

### N/A values at read

In [22]:
df = pd.read_csv('data2.csv')
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address
0,26589651,10/31/2013 02:08:41 AM,NaN,NYPD,New York City Police Department,NaN,Loud Talking,Street/Sidewalk,11432,90-03 169 STREET
1,26593698,10/31/2013 02:01:04 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,0,11378,58 AVENUE
2,26594139,10/31/2013 02:00:24 AM,10/31/2013 02:40:32 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10032,4060 BROADWAY
3,26595721,10/31/2013 01:56:23 AM,10/31/2013 02:21:48 AM,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Horn,Street/Sidewalk,10023,WEST 72 STREET
4,26532099,10/22/2013 11:55:50 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint,Street,NO CLUE,NO BUILDIN OBSERVER HIGHWAY

In [24]:
na_values = ['NO CLUE', 'N/A', '0']
df = pd.read_csv('data2.csv', na_values=na_values, dtype={'Incident Zip': str})
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address
0,26589651,10/31/2013 02:08:41 AM,NaN,NYPD,New York City Police Department,NaN,Loud Talking,Street/Sidewalk,11432,90-03 169 STREET
1,26593698,10/31/2013 02:01:04 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,NaN,11378,58 AVENUE
2,26594139,10/31/2013 02:00:24 AM,10/31/2013 02:40:32 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10032,4060 BROADWAY
3,26595721,10/31/2013 01:56:23 AM,10/31/2013 02:21:48 AM,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Horn,Street/Sidewalk,10023,WEST 72 STREET
4,26532099,10/22/2013 11:55:50 AM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint,Street,NaN,NO BUILDIN OBSERVER HIGHWAY