In [25]:
import pandas as pd

train_df = pd.read_csv('../../data/titanic_train.csv')
test_df = pd.read_csv('../../data/titanic_test.csv')

### 8.a Drop unwanted columns

In [26]:
train_df = train_df.drop(['Cabin', 'Name', 'Ticket', 'Fare', 'PassengerId'], axis=1)
test_df = test_df.drop(['Cabin', 'Name', 'Ticket', 'Fare', 'PassengerId'], axis=1)

In [27]:
train_df[5:8]

   Survived  Pclass   Sex   Age  SibSp  Parch Embarked
5         0       3  male   NaN      0      0        Q
6         0       1  male  54.0      0      0        S
7         0       3  male   2.0      3      1        S

### 8.b Handling missing values

In [28]:
train_df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Embarked      2
dtype: int64

In [29]:
from sklearn.impute import SimpleImputer

# train_df
mean_imputer = SimpleImputer(strategy='mean')
train_df['Age'] = mean_imputer.fit_transform(train_df[['Age']])

train_df[5:8]

   Survived  Pclass   Sex        Age  SibSp  Parch Embarked
5         0       3  male  29.699118      0      0        Q
6         0       1  male  54.000000      0      0        S
7         0       3  male   2.000000      3      1        S

In [30]:
# test_df
mean_imputer = SimpleImputer(strategy='mean')
test_df['Age'] = mean_imputer.fit_transform(test_df[['Age']])

test_df[:3]

   Pclass     Sex   Age  SibSp  Parch Embarked
0       3    male  34.5      0      0        Q
1       3  female  47.0      1      0        S
2       2    male  62.0      0      0        Q

In [31]:
# Another way (another imputer - for the other categorical values as well)

freq_imputer = SimpleImputer(strategy='most_frequent')
train_df.iloc[:, :] = freq_imputer.fit_transform(train_df)
test_df.iloc[:, :] = freq_imputer.fit_transform(test_df)

In [32]:
train_df[5:8]

   Survived  Pclass   Sex        Age  SibSp  Parch Embarked
5         0       3  male  29.699118      0      0        Q
6         0       1  male  54.000000      0      0        S
7         0       3  male   2.000000      3      1        S

In [34]:
train_df.isnull().sum(), test_df.isnull().sum()

(Survived    0
 Pclass      0
 Sex         0
 Age         0
 SibSp       0
 Parch       0
 Embarked    0
 dtype: int64,
 Pclass      0
 Sex         0
 Age         0
 SibSp       0
 Parch       0
 Embarked    0
 dtype: int64)

### 9. Categorical and numerical columns

In [35]:
cat_cols = train_df.select_dtypes(include=["object", "str", "bool"]).columns.tolist()
num_cols = train_df.select_dtypes(include=["int", "float"]).columns.tolist()

In [36]:
print("Categorical Columns:", cat_cols)
print("-" * 120)
print("Numerical Columns:", num_cols)

Categorical Columns: ['Sex', 'Embarked']
------------------------------------------------------------------------------------------------------------------------
Numerical Columns: ['Survived', 'Pclass', 'Age', 'SibSp', 'Parch']

In [37]:
train_df[:3]

   Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S

### 10. Checking Cardinality of Categorical Features

In [38]:
print("Cardinality of features in numerical data is: ")
print(train_df.select_dtypes(include=["int", "float"]).nunique())
print("-" * 50)

print("Cardinality of features in categorical data is: ")
print(test_df.select_dtypes(include=["object", "str", "bool"]).nunique())

Cardinality of features in numerical data is:
Survived     2
Pclass       3
Age         89
SibSp        7
Parch        7
dtype: int64
--------------------------------------------------
Cardinality of features in categorical data is:
Sex         2
Embarked    3
dtype: int64

### 11. Handle categorical variables

- drop
- dummy
- ordinal encoding
- one-hot encoding
- label encoding

In [39]:
train_df[:3]

   Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S

In [40]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
ordinal_cat_cols = ["Pclass", "SibSp", "Parch"]

train_df[ordinal_cat_cols] = train_df[ordinal_cat_cols].apply(label_encoder.fit_transform)
test_df[ordinal_cat_cols] = test_df[ordinal_cat_cols].apply(label_encoder.fit_transform)

In [41]:
train_df[:3]

   Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       2    male  22.0      1      0        S
1         1       0  female  38.0      1      0        C
2         1       2  female  26.0      0      0        S

In [42]:
nominal_cat_cols = ["Sex", "Embarked"]

train_df = pd.get_dummies(train_df, columns=nominal_cat_cols)
test_df = pd.get_dummies(test_df, columns=nominal_cat_cols)

In [43]:
train_df[:5]

,Survived,Pclass,Age,SibSp,Parch,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,2,22.0,1,0,False,True,False,False,True
1,1,0,38.0,1,0,True,False,True,False,False
2,1,2,26.0,0,0,True,False,False,False,True
3,1,0,35.0,1,0,True,False,False,False,True
4,0,2,35.0,0,0,False,True,False,False,True

In [44]:
test_df[:5]

,Pclass,Age,SibSp,Parch,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,2,34.5,0,0,False,True,False,True,False
1,2,47.0,1,0,True,False,False,False,True
2,1,62.0,0,0,False,True,False,True,False
3,2,27.0,0,0,False,True,False,False,True
4,2,22.0,1,1,True,False,False,False,True

### 12. Selecting Features & Labels For Model Training

In [45]:
X = train_df.drop(columns=["Survived"])
y = train_df["Survived"]

In [48]:
X[:3]

,Pclass,Age,SibSp,Parch,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,2,22.0,1,0,False,True,False,False,True
1,0,38.0,1,0,True,False,True,False,False
2,2,26.0,0,0,True,False,False,False,True

In [49]:
y[:3]

0    0
1    1
2    1
Name: Survived, dtype: int64